# Generated by Django 3.1.1 on 2020-09-16 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('gbp_conversion', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_date', models.DateField(verbose_name='Wedding Date')),
                ('wedding_name', models.CharField(max_length=255, verbose_name='Description')),
                ('spouse_x_name', models.CharField(max_length=50)),
                ('spouse_y_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False, help_text='`Inactive` gift lists allow building the list prior to making it public')),
            ],
        ),
        migrations.CreateModel(
            name='GiftListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1, help_text='Most of the times only one existence of any product will be added to the list', verbose_name='Quant')),
                ('price', models.DecimalField(decimal_places=2, help_text='Gift price must remain unchanged', max_digits=8, verbose_name='Price')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='When added')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.giftlist')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('recipient', models.CharField(help_text='The name or names typically following `Dear ...`', max_length=80, verbose_name='Guest(s) names')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.giftlist')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1, help_text='Most of the times only one existence of any item will be purchased by a Guest', verbose_name='Quantity')),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.guest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.giftlistitem', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Includes taxes', max_digits=8, verbose_name='Price')),
                ('qty', models.PositiveSmallIntegerField(default=0, verbose_name='Quant in Stock')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.brand', verbose_name='Brand')),
                ('currency', models.ForeignKey(default='GBP', on_delete=django.db.models.deletion.CASCADE, to='glist.currency', verbose_name='Currency')),
            ],
        ),
        migrations.AddField(
            model_name='giftlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glist.product'),
        ),
    ]
