# Generated by Django 3.1.1 on 2020-09-17 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlistitem',
            name='qty_purchased',
            field=models.PositiveSmallIntegerField(default=0, help_text='Tracks how many are already ordered', verbose_name='Purchases'),
        ),
        migrations.AlterField(
            model_name='giftlistitem',
            name='gift_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='glist.giftlist'),
        ),
        migrations.AlterField(
            model_name='giftlistitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gift price must remain unchanged', max_digits=8, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
