# Generated by Django 3.1.1 on 2020-09-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glist', '0003_giftlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlist',
            name='active',
            field=models.BooleanField(default=True, help_text='`Inactive` gift lists allow building the list prior to making it public'),
        ),
    ]
